# Generated by Django 4.1.7 on 2023-08-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tripcategory_trip_trip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtrips',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_featured_trips', to='booking.bus'),
        ),
    ]
