# Generated by Django 4.1.7 on 2023-08-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_featuredtrips_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaqsCategory', to='booking.faqscategory'),
        ),
    ]
