# Generated by Django 4.1.7 on 2023-08-13 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_cities_is_active_alter_faqs_question_alter_faqs_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busimages',
            options={'verbose_name': 'Bus Images', 'verbose_name_plural': 'Bus Images'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'Faq', 'verbose_name_plural': 'Faqs'},
        ),
        migrations.AlterModelOptions(
            name='faqscategory',
            options={'verbose_name': 'Faqs Category', 'verbose_name_plural': 'Faq Categories'},
        ),
        migrations.AlterModelOptions(
            name='featuredtrips',
            options={'verbose_name': 'Featured Trip', 'verbose_name_plural': 'Featured Trips'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='tripcategory',
            options={'verbose_name': 'Trip Category', 'verbose_name_plural': 'Trip Categories'},
        ),
        migrations.AlterModelOptions(
            name='tripinsurance',
            options={'verbose_name': 'Trip Insurance', 'verbose_name_plural': 'Trip Insurances'},
        ),
        migrations.AlterModelOptions(
            name='userlicense',
            options={'verbose_name': 'User License', 'verbose_name_plural': 'UserLicenses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cities',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupons',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faqs',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featuredtrips',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='featuredtrips',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='insurance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payments',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='refund',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='route',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stopcharges',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stopcharges',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stops',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripinsurance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tripinsurance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlicense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userlicense',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
