# Generated by Django 4.1.7 on 2023-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_insurance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Booked', 'Booked')], default='Available', max_length=50, null=True),
        ),
    ]
