# Generated by Django 4.1.7 on 2023-08-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_order_paid_amount_alter_payments_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Refund', 'Refund')], default='Pending', max_length=50),
        ),
    ]
