# Generated by Django 4.1.7 on 2023-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_refund_refund_id_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=150),
        ),
    ]
