# Generated by Django 4.1.7 on 2023-08-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_featuredtrips_trip_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order_user',
            field=models.BooleanField(default=False),
        ),
    ]
