# Generated by Django 4.1.7 on 2023-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_user_is_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='is_driver_required',
            field=models.BooleanField(default=True),
        ),
    ]
