# Generated by Django 4.1.7 on 2023-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_trip_is_driver_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_two_way_trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('One-Way', 'One-Way'), ('Round-Trip', 'Round-Trip'), ('Self-Drive', 'Self-Drive')], default='One-Way', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='scale',
            field=models.CharField(blank=True, choices=[('Hour', 'hour'), ('Kilometer', 'kilometer')], default='Hour', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='scale',
            field=models.CharField(blank=True, choices=[('Hour', 'hour'), ('Kilometer', 'kilometer')], default='Hour', max_length=50, null=True),
        ),
    ]
