# Generated by Django 4.1.7 on 2023-09-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_bus_self_drive_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='per_scale_charges',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='scale',
        ),
        migrations.CreateModel(
            name='BusCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(blank=True, choices=[('Hour', 'hour'), ('Kilometer', 'kilometer')], default='Hour', max_length=50, null=True)),
                ('per_scale_charges', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
            options={
                'unique_together': {('bus', 'scale')},
            },
        ),
    ]
