# Generated by Django 4.1.7 on 2023-09-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_bus_per_scale_charges_remove_bus_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscharges',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_charges', to='booking.bus'),
        ),
    ]
