# Generated by Django 4.1.7 on 2023-09-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_xero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero',
            name='state',
        ),
        migrations.AddField(
            model_name='xero',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
