# Generated by Django 4.1.7 on 2023-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_remove_xero_state_xero_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero',
            name='code_verifier',
        ),
        migrations.AddField(
            model_name='xero',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
