# Generated by Django 4.1.7 on 2023-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_remove_xero_code_verifier_xero_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xero',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='xero',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
