# Generated by Django 4.1.7 on 2023-10-21 07:53

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_trip_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='identity_card',
            field=models.FileField(default='', upload_to=booking.models.trip_path),
        ),
    ]
